# version: '3.8'

# services:
#   mongo:
#     image: mongo:latest
#     restart: always
#     ports:
#       - 27017:27017
#     environment:
#       MONGO_INITDB_DATABASE: state_suggestion
#     volumes:
#       - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
#     networks:
#       - my_network

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     restart: always
#     ports:
#       - 8080:8080
#     depends_on:
#       - mongo
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/state_suggestion
#     networks:
#       - my_network

#   frontend:
#     build:
#       context: ./suggestion_app
#       dockerfile: Dockerfile
#     networks:
#       - my_network

#   nginx:
#     image: nginx:latest
#     ports:
#       - 80:80
#     depends_on:
#       - frontend
#       - backend
#     volumes:
#       - ./nginx/config:/etc/nginx/conf.d
#     networks:
#       - my_network

# networks:
#   my_network:
#     driver: bridge


version: '3'
services:
  frontend:
    build:
      context: ./suggestion_app
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8081:8081"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend